### ISSUE TITLE
Can't add/delete pops

### ISSUE THREAD

**Issue by Javier2002xd** [Ne00n/woodCDN#10]
Hi i can't add/delete pops
![image](https://user-images.githubusercontent.com/99488329/160499334-618ef523-825d-4895-8ba6-f0634eac9a01.png)

I can add pops but i need to put <latitude> <longitude>but i can't delete it.
![image](https://user-images.githubusercontent.com/99488329/160499489-36580243-c72a-4f0c-972d-13af81f9eb8e.png)

**Comment by Ne00n** [comment]
First, don't post IP addresses and second, you are using the wrong branch.
gdnsd works different and does not work with geo coordinates.

the master branch uses pdns and the geodns branch uses gdnsd with a different database.
