### ISSUE TITLE
Update Network to Anycast

### ISSUE THREAD

**Issue by bitUpsurge** [Ne00n/woodCDN#5]
Please upgrade network to Anycast for highest accuracy in determining user’s geolocation.

Anycast is a method for addressing and routing. In this method, the same IP address is allocated to a group of server nodes which, within a CDN framework, act as a series of servers in different datacenters throughout the world. The traffic sent to this IP address is responded by the topologically closest server to the transmitter of the request. As a result, ArvanCloud IP addresses are simultaneously advertised worldwide, and every user can connect to the closest edge server and get services through the first connection.

**Comment by Ne00n** [comment]
There is no technical limitation in this software to not use anycast.
