### ISSUE TITLE
DDoS Protection

### ISSUE THREAD

**Issue by Javier2002xd** [Ne00n/woodCDN#8]
Hello! If i setup 20 machine with this CDN can i use it to protected my website? 
Like a reverse proxy

**Comment by Ne00n** [comment]
Technically Yes.

**Comment by Javier2002xd** [comment]
Another Question.
Where is Nginx Nodes.
I need to install nginx on all machines?
And DNS Nodes?

**Comment by Javier2002xd** [comment]
And any idea how can i resolve this error?
Failed to bind() TCP DNS socket to 0.0.0.0:53
https://imgur.com/a/ztcXQJV
